name: TTS via repository_dispatch

on:
  repository_dispatch:
    types: [start_ollama]

jobs:
  tts_and_respond:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python with pip caching
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # enables pip dependency cache

      - name: Show received payload (for debugging)
        run: |
          echo "Received event payload:"
          echo "CHAT_ID: ${{ github.event.client_payload.telegram_chat_id }}"
          echo "ORIGINAL_MSG: ${{ github.event.client_payload.original_message }}"
          echo "VOICE: ${{ github.event.client_payload.voice || 'expr-voice-2-f' }}"

      - name: Install dependencies
        run: |
          pip install soundfile requests

      - name: Generate TTS audio
        run: |
          python - << 'EOF'
          import os, soundfile as sf
          from kittentts import KittenTTS

          chat_id = os.environ["CHAT_ID"]
          text = os.environ["ORIG_MSG"]
          voice = os.environ.get("VOICE", "expr-voice-2-f")

          fname = "tts_output.wav"
          m = KittenTTS("KittenML/kitten-tts-nano-0.1")
          audio = m.generate(text, voice=voice)
          sf.write(fname, audio, 24000)

          print(f"Generated file: {fname}")
          EOF
        env:
          CHAT_ID: ${{ github.event.client_payload.telegram_chat_id }}
          ORIG_MSG: ${{ github.event.client_payload.original_message }}
          VOICE: ${{ github.event.client_payload.voice }}

      - name: Send voice message to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ github.event.client_payload.telegram_chat_id }}
        run: |
          curl -s -X POST \
            -H "Content-Type: multipart/form-data" \
            -F chat_id="$CHAT_ID" \
            -F voice="@tts_output.wav" \
            "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendVoice"
