name: TTS to Telegram

on:
  workflow_dispatch:
    inputs:
      text:
        description: "Text to synthesize"
        required: true
      voice:
        description: "Voice"
        default: "expr-voice-2-f"
      chat_id:
        description: "Telegram chat ID"
        required: true

jobs:
  tts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install soundfile
          pip install https://github.com/KittenML/KittenTTS/releases/download/0.1/kittentts-0.1.0-py3-none-any.whl
          pip install requests

      - name: Generate TTS Audio
        run: |
          python - << 'EOF'
          from kittentts import KittenTTS
          import soundfile as sf

          text = "${{ inputs.text }}"
          voice = "${{ inputs.voice }}"
          filename = "output.wav"

          m = KittenTTS("KittenML/kitten-tts-nano-0.1")
          audio = m.generate(text, voice=voice)
          sf.write(filename, audio, 24000)
          EOF

      - name: Send Voice to Telegram
        env:
          CHAT_ID: ${{ inputs.chat_id }}
        run: |
          BOT_TOKEN="8276916788:AAFqYhxqLjQMtw6BTmFzMf1AyYHWDhDVhtA"
          curl -s -X POST \
            -H "Content-Type: multipart/form-data" \
            -F chat_id="$CHAT_ID" \
            -F voice="@output.wav" \
            "https://api.telegram.org/bot$BOT_TOKEN/sendVoice"
